blueprint:
  name: Geolocalização para Status Presente
  description: Muda o status de uma pessoa para presente com base na geolocalização de um dispositivo.
  domain: automation
  input:
    person_entity:
      name: Pessoa
      description: Selecione a entidade pessoa que será atualizada.
      selector:
        entity:
          domain: person
    device_tracker_entity:
      name: Dispositivo Móvel
      description: Selecione a entidade do dispositivo móvel com geolocalização.
      selector:
        entity:
          domain: device_tracker

trigger:
  platform: state
  entity_id: !input device_tracker_entity
  to: 'home'

action:
  - service: person.set_status
    data:
      entity_id: !input person_entity
      status: home
