blueprint:
  name: Ligar e desligar switch com sensor mmWave e iluminação
  description: Liga o switch quando o sensor mmWave detecta presença e a iluminação é inferior a 100 lux. Desliga o switch quando não há presença.
  domain: automation
  input:
    sensor_presence:
      name: Sensor mmWave de Presença
      description: O sensor mmWave que detecta presença.
      selector:
        entity:
          domain: binary_sensor
    sensor_illuminance:
      name: Sensor de Iluminação
      description: O sensor que mede o nível de iluminação em lux.
      selector:
        entity:
          domain: sensor
    switch:
      name: Switch
      description: O switch que será controlado com base na presença e na iluminação.
      selector:
        entity:
          domain: switch

trigger:
  - platform: state
    entity_id: !input sensor_presence
    to: 'on'
  - platform: state
    entity_id: !input sensor_presence
    to: 'off'

condition:
  - condition: template
    value_template: "{{ states('!input sensor_illuminance') | int < 100 }}"

action:
  - choose:
      - conditions:
          - condition: state
            entity_id: !input sensor_presence
            state: 'on'
          - condition: template
            value_template: "{{ states('!input sensor_illuminance') | int < 100 }}"
        sequence:
          - service: switch.turn_on
            target:
              entity_id: !input switch
      - conditions:
          - condition: state
            entity_id: !input sensor_presence
            state: 'off'
        sequence:
          - service: switch.turn_off
            target:
              entity_id: !input switch
