blueprint:
  name: MMWAVE Corredor Quartos
  description: Automação para ligar e desligar luzes no corredor dos quartos com base na presença detectada pelo sensor mmWave.
  domain: automation
  input:
    mmwave_sensor:
      name: Sensor mmWave
      selector:
        entity:
          domain: binary_sensor
    light_entity:
      name: Luz
      selector:
        entity:
          domain: light
trigger:
  - platform: state
    entity_id: !input mmwave_sensor
action:
  - choose:
      - conditions:
          - condition: state
            entity_id: !input mmwave_sensor
            state: "on"
        sequence:
          - service: light.turn_on
            target:
              entity_id: !input light_entity
      - conditions:
          - condition: state
            entity_id: !input mmwave_sensor
            state: "off"
        sequence:
          - service: light.turn_off
            target:
              entity_id: !input light_entity
mode: single
