blueprint:
  name: MMWAVE 
  description: Automação para ligar e desligar múltiplos dispositivos com base na presença detectada pelo sensor mmWave, com restrição de tempo.
  domain: automation
  input:
    mmwave_sensor:
      name: Sensor mmWave
      selector:
        entity:
          domain: binary_sensor
    switch_entities:
      name: Dispositivos de Switch
      selector:
        target:
          entity:
            domain: switch
    start_time:
      name: Hora de Início
      description: Hora do dia em que a automação começa a funcionar.
      selector:
        time:
    end_time:
      name: Hora de Término
      description: Hora do dia em que a automação para de funcionar.
      selector:
        time:
trigger:
  - platform: state
    entity_id: !input mmwave_sensor
condition:
  - condition: time
    after: !input start_time
    before: !input end_time
action:
  - choose:
      - conditions:
          - condition: state
            entity_id: !input mmwave_sensor
            state: "on"
        sequence:
          - delay: "00:00:01"  # Atraso de 1 segundo
          - service: switch.turn_on
            target: !input switch_entities
      - conditions:
          - condition: state
            entity_id: !input mmwave_sensor
            state: "off"
        sequence:
          - delay: "00:00:01"  # Atraso de 1 segundo
          - service: switch.turn_off
            target: !input switch_entities
mode: restart

