blueprint:
  name: Multi-Device Switch Control
  description: Controla múltiplos dispositivos com um único switch e verifica os estados. Criado por Ricardo Esper em 13/05/2024.
  domain: automation
  input:
    target_switch:
      name: Switch Controlador
      description: O switch que controlará os outros dispositivos.
      selector:
        entity:
          domain: switch
    controlled_devices:
      name: Dispositivos Controlados
      description: Lista de dispositivos que serão controlados pelo switch.
      selector:
        target:
          entity:
            domain: switch

trigger:
  - platform: state
    entity_id: !input target_switch
    to: 'on'
    from: 'off'
  - platform: state
    entity_id: !input target_switch
    to: 'off'
    from: 'on'

action:
  - service: homeassistant.toggle
    target: !input controlled_devices
  - delay: 00:00:01  # Espera 1 segundo para verificar o estado
  - choose:
      - conditions:
          - condition: state
            entity_id: !input target_switch
            state: 'on'
        sequence:
          - condition: template
            value_template: >
              {{ expand('controlled_devices') | selectattr('state', 'equalto', 'on') | list | count == expand('controlled_devices') | list | count }}
          - service: notify.persistent_notification
            data:
              message: "Todos os dispositivos estão LIGADOS conforme esperado."
      - conditions:
          - condition: state
            entity_id: !input target_switch
            state: 'off'
        sequence:
          - condition: template
            value_template: >
              {{ expand('controlled_devices') | selectattr('state', 'equalto', 'off') | list | count == expand('controlled_devices') | list | count }}
          - service: notify.persistent_notification
            data:
              message: "Todos os dispositivos estão DESLIGADOS conforme esperado."
