blueprint:
  name: Sincronização de Múltiplos Interruptores
  description: Mantém 2 a 5 interruptores sincronizados, garantindo que todos estejam sempre no mesmo estado.
  domain: automation
  input:
    switches:
      name: Interruptores
      description: Selecione de 2 a 5 interruptores para serem sincronizados.
      selector:
        entity:
          domain: switch
          multiple: true

trigger:
  - platform: state
    entity_id: !input 'switches'

condition: []

action:
  - variables:
      target_state: "{{ trigger.to_state.state }}"
  - condition: template
    value_template: "{{ expand(switches) | selectattr('state', '!=', target_state) | list | count > 0 }}"
  - repeat:
      count: "{{ expand(switches) | selectattr('state', '!=', target_state) | list | count }}"
      sequence:
        - service: "switch.turn_{{ target_state }}"
          data:
            entity_id: "{{ expand(switches) | selectattr('state', '!=', target_state) | map(attribute='entity_id') | list }}"

# Blueprint criado por Ricardo Esper em 13 de Maio de 2024
