blueprint:
  name: Controle Flexível de Dispositivos com Sensor mmWave
  description: Aciona dispositivos com base na iluminância, presença e distância detectadas por um sensor mmWave.
  domain: automation
  input:
    mmwave_sensor:
      name: Sensor mmWave
      description: Selecione o sensor mmWave para monitorar mudanças.
      selector:
        entity:
          domain: sensor
    luminance_threshold:
      name: Limiar de Iluminância
      description: Valor de iluminância para acionar os dispositivos.
      default: 100
      selector:
        number:
          min: 0
          max: 1000
          unit_of_measurement: lux
    presence_state:
      name: Estado de Presença
      description: Estado de presença para acionar os dispositivos (por exemplo, 'detected').
      default: 'detected'
      selector:
        text:
    distance_threshold:
      name: Limiar de Distância
      description: Valor de distância para acionar dispositivos.
      default: 2
      selector:
        number:
          min: 0
          max: 10
          unit_of_measurement: meters
    devices_to_control:
      name: Dispositivos a Controlar
      description: Selecione os dispositivos que serão controlados.
      selector:
        target:

trigger:
  - platform: numeric_state
    entity_id: !input 'mmwave_sensor'
    attribute: illuminance
    above: !input 'luminance_threshold'
  - platform: state
    entity_id: !input 'mmwave_sensor'
    attribute: presence
    to: !input 'presence_state'
  - platform: numeric_state
    entity_id: !input 'mmwave_sensor'
    attribute: distance
    below: !input 'distance_threshold'

action:
  - service: homeassistant.turn_on
    target: !input 'devices_to_control'

