blueprint:
  name: Sensor MMWAVE by Esper
  description: Aciona switches com base na presença e iluminância detectadas por um sensor. Liga quando a luminosidade é inferior a 100 lx e há presença; desliga quando não há presença. Garante que os atributos necessários estão presentes.
  domain: automation
  input:
    sensor_entity:
      name: Entidade do Sensor
      description: Selecione a entidade do sensor que monitora presença e iluminância.
      selector:
        entity:
          domain: sensor

    devices_to_control:
      name: Switches a Controlar
      description: Selecione os switches que serão controlados por esta automação.
      selector:
        target:
          entity:
            domain: switch

trigger:
  - platform: state
    entity_id: !input 'sensor_entity'
    attribute: presence
    to: 'detected'
  - platform: state
    entity_id: !input 'sensor_entity'
    attribute: presence
    to: 'not_detected'
  - platform: numeric_state
    entity_id: !input 'sensor_entity'
    attribute: illuminance
    below: 100

condition:
  - condition: template
    value_template: >
      {% set sensor = states.sensor | selectattr('entity_id', 'eq', states[trigger.entity_id].entity_id) | first %}
      {{ 'presence' in sensor.attributes and 'illuminance' in sensor.attributes }}

  - condition: and
    conditions:
      - condition: state
        entity_id: !input 'sensor_entity'
        attribute: presence
        state: 'detected'
      - condition: numeric_state
        entity_id: !input 'sensor_entity'
        attribute: illuminance
        below: 100

action:
  - choose:
      - conditions:
          - condition: state
            entity_id: !input 'sensor_entity'
            attribute: presence
            state: 'detected'
        sequence:
          - service: homeassistant.turn_on
            target: !input 'devices_to_control'
      - conditions:
          - condition: state
            entity_id: !input 'sensor_entity'
            attribute: presence
            state: 'not_detected'
        sequence:
          - service: homeassistant.turn_off
            target: !input 'devices_to_control'
