blueprint:
  name: Controle Sensor mmwave by Esper
  description: Aciona switches com base na presença e iluminância detectadas por um dispositivo sensor. Liga quando a luminosidade é inferior a 100 lx e há presença; desliga quando não há presença.
  domain: automation
  input:
    sensor_device:
      name: Dispositivo Sensor
      description: Selecione o dispositivo sensor que monitora presença e iluminância.
      selector:
        device: {}

    devices_to_control:
      name: Switches a Controlar
      description: Selecione os switches que serão controlados por esta automação.
      selector:
        target:
          entity:
            domain: switch

trigger:
  - platform: state
    entity_id: !input 'sensor_device'
    attribute: presence
    to: 'detected'
  - platform: state
    entity_id: !input 'sensor_device'
    attribute: presence
    to: 'not_detected'
  - platform: numeric_state
    entity_id: !input 'sensor_device'
    attribute: illuminance
    below: 100

condition:
  - condition: and
    conditions:
      - condition: state
        entity_id: !input 'sensor_device'
        attribute: presence
        state: 'detected'
      - condition: numeric_state
        entity_id: !input 'sensor_device'
        attribute: illuminance
        below: 100

action:
  - choose:
      - conditions:
          - condition: state
            entity_id: !input 'sensor_device'
            attribute: presence
            state: 'detected'
        sequence:
          - service: homeassistant.turn_on
            target: !input 'devices_to_control'
      - conditions:
          - condition: state
            entity_id: !input 'sensor_device'
            attribute: presence
            state: 'not_detected'
        sequence:
          - service: homeassistant.turn_off
            target: !input 'devices_to_control'
