blueprint:
  name: Sensor Automation by Esper
  description: Aciona dispositivos quando há detecção de presença após o pôr do sol e até uma hora após o nascer do sol, e os desliga se não houver presença por mais de 30 segundos.
  domain: automation
  input:
    presence_sensor:
      name: Sensor de presença
      description: Escolha o sensor de presença
      selector:
        entity:
          domain: binary_sensor
          device_class: motion
    controlled_entities:
      name: Entidades controladas
      description: Selecione os dispositivos ou entidades a serem controlados
      selector:
        target:
          entity:
            domain: 
              - switch
              - light
              - media_player

trigger:
  - platform: state
    entity_id: !input presence_sensor
    to: 'on'
  - platform: state
    entity_id: !input presence_sensor
    to: 'off'
    for: "00:00:30"

condition:
  - condition: or
    conditions:
      - condition: and
        conditions:
          - condition: state
            entity_id: !input presence_sensor
            state: 'on'
          - condition: or
            conditions:
              - condition: sun
                after: sunset
              - condition: sun
                before: sunrise
                before_offset: "01:00:00"
      - condition: state
        entity_id: !input presence_sensor
        state: 'off'

action:
  - choose:
      - conditions:
          - condition: state
            entity_id: !input presence_sensor
            state: 'on'
        sequence:
          - service: homeassistant.turn_on
            target: !input controlled_entities
      - conditions:
          - condition: state
            entity_id: !input presence_sensor
            state: 'off'
        sequence:
          - service: homeassistant.turn_off
            target: !input controlled_entities

mode: restart
